### ISSUE TITLE
Can't `bundle install` on my Yosemite machine

### ISSUE THREAD

**Issue by parkr** [brightroll/screens#13]
Can't find the `dns_sd.h` header file. But I can.

```text
~$ gem install dnssd -v 2.0
Building native extensions.  This could take a while...
ERROR:  Error installing dnssd:
	ERROR: Failed to build gem native extension.

    /usr/local/var/rbenv/versions/2.1.2-github1/bin/ruby extconf.rb
checking for dns_sd.h... no
unable to find dnssd header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/var/rbenv/versions/2.1.2-github1/bin/ruby
	--with-warnings
	--without-warnings
	--with-dnssd-dir
	--without-dnssd-dir
	--with-dnssd-include
	--without-dnssd-include=${dnssd-dir}/include
	--with-dnssd-lib
	--without-dnssd-lib=${dnssd-dir}/lib

extconf failed, exit code 1

Gem files will remain installed in /usr/local/var/rbenv/versions/2.1.2-github1/lib/ruby/gems/2.1.0/gems/dnssd-2.0 for inspection.
Results logged to /usr/local/var/rbenv/versions/2.1.2-github1/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/dnssd-2.0/gem_make.out
~$ ls /usr/include/dns_sd.h
/usr/include/dns_sd.h
~$ ruby -v
ruby 2.1.2p95-github (development) [x86_64-darwin13.0]
```

Any ideas?

**Comment by sodabrew** [comment]
Mavericks or Yosemite? https://github.com/tenderlove/dnssd/issues/16

**Comment by sodabrew** [comment]
I haven't tried building on Yosemite yet, my current Screens servers are on Mavericks, but I will give it a spin. I do know that in Yosemite, mDNS was replaced with discoveryd. I don't know if they also changed the C API.

**Comment by parkr** [comment]
It is on Yosemite – that might be the problem :(

**Comment by sodabrew** [comment]
I am migrating our office Screens to Yosemite soon, so this is a priority to help resolve!

**Comment by parkr** [comment]
> I am migrating our office Screens to Yosemite soon, so this is a priority to help resolve!

From the other issuee you mention above, it appears that it was my modified MRI. I run github/ruby, which seems to have nontraditional include paths or something. I switched to MRI 2.1.5 and all was kosher.

**Comment by sodabrew** [comment]
Sweet! Hope you like the app. Let me know if you need any help or want suggestions on things to hack on to improve it (I have quite a list ;)).

**Comment by parkr** [comment]
@sodabrew Working on adding https://github.com/zquestz/omniauth-google-oauth2 – Google OpenID is borked. Running into `session[]` issues now.

**Comment by sodabrew** [comment]
Awesome! Migrating to OAuth has been on my todo list. There isn't much of a user framework right now, basically just true/false from the external auth.

**Comment by sodabrew** [comment]
Mind if I close this Yosemite related issue and look forward to your omniauth PR?

**Comment by parkr** [comment]
Yep!
